export type AppLanguage = 'pt-BR' | 'en-US' | 'es-ES'

const messages: Record<AppLanguage, Record<string, string>> = {
  'pt-BR': {
    'language.title': 'Idioma', 'language.pt': 'Português', 'language.en': 'English', 'language.es': 'Español',
    'nav.home': 'Início', 'nav.workouts': 'Treinos', 'nav.data': 'Dados', 'nav.settings': 'Ajustes', 'nav.label': 'Navegação principal',
    'home.register': 'Registrar treino', 'home.period': 'Período do resumo', 'home.filter': 'Filtrar quantidade de NSBs', 'home.all': 'Todos', 'home.expand': 'Mostrar quantidades', 'home.collapse': 'Recolher quantidades', 'home.analysis': 'Modo de análise', 'home.compare': 'Comparar anos', 'home.evolution': 'Evolução', 'home.statistics': 'Estatísticas',
    'period.all': 'Todo o período', 'period.year': 'Este ano', 'period.month': 'Este mês',
    'history.eyebrow': 'Registros detalhados', 'history.title': 'Treinos', 'history.lead': 'Consulte, ajuste ou mova registros detalhados para a lixeira. As análises ficam concentradas na tela inicial.', 'history.loading': 'Carregando dados locais…',
    'data.eyebrow': 'Propriedade dos dados', 'data.title': 'Backup e restauração', 'data.lead': 'Exporte uma cópia completa do seu histórico. Uma importação segura combina registros pelo identificador e mantém a versão mais recente.', 'data.export': 'Exportar backup JSON', 'data.import': 'Importar backup', 'data.restore': 'Restaurar backup', 'data.summary': 'Importar combina registros. Restaurar substitui treinos, históricos e preferências após criar uma cópia de segurança.',
    'settings.eyebrow': 'Ajustes', 'settings.title': 'Preferências', 'settings.appearance': 'Aparência', 'settings.system': 'Automático', 'settings.light': 'Claro', 'settings.dark': 'Escuro', 'settings.text': 'Texto', 'settings.fontSize': 'Tamanho do texto', 'settings.fontScale': '{value}% do tamanho padrão', 'settings.palette': 'Paleta', 'settings.visualPalette': 'Aplicar nos gráficos e calendário', 'settings.sound': 'Som', 'settings.soundAlerts': 'Avisos sonoros', 'settings.soundVolume': 'Volume dos avisos', 'settings.soundProfile': 'Perfil sonoro', 'settings.testSound': 'Testar perfil {name}', 'settings.targets': 'Metas', 'settings.targetsHint': 'Toque em uma quantidade para removê-la. Adicione qualquer valor quando precisar.', 'settings.defaultTargets': 'Metas padrão', 'settings.removeTarget': 'Remover meta {target}', 'settings.addTarget': 'Adicionar meta', 'settings.targetExample': 'Ex.: 75', 'settings.add': 'Adicionar', 'settings.presets': 'Presets', 'settings.presetTarget': 'Quantidade do preset', 'settings.strategiesFor': 'Estratégias para {target} NSBs.', 'settings.new': 'Novo', 'settings.presetName': 'Nome do preset', 'settings.delete': 'Excluir', 'settings.presetGoalType': 'Tipo de meta do preset',
    'workout.back': 'Voltar ao início', 'workout.applyPreset': 'Aplicar preset', 'workout.select': 'Selecionar', 'workout.total': 'Quantidade total', 'workout.timer': 'Cronômetro', 'workout.warmup': 'Warm-up', 'workout.resume': 'Retomar', 'workout.start': 'Iniciar', 'workout.pause': 'Pausar', 'workout.reset': 'Zerar', 'workout.dateTime': 'Data e hora', 'workout.totalTime': 'Tempo total', 'workout.sets': 'Estrutura de sets', 'workout.strategy': 'Registre a estratégia para compará-la no futuro.', 'workout.addGroup': 'Adicionar grupo', 'workout.group': 'Grupo', 'workout.remove': 'Remover', 'workout.setTotal': 'Total dos sets', 'workout.guidedPacing': 'Pacing guiado', 'workout.pacingGoal': 'Meta de pacing', 'workout.ready': 'Pronto', 'workout.prepare': 'Preparar', 'workout.inSet': 'Em set', 'workout.rest': 'Descanso', 'workout.paused': 'Pausado', 'workout.complete': 'Concluído', 'workout.soundAlerts': 'Avisos sonoros', 'workout.warmupNote': 'O cronômetro inicia o warm-up de {seconds}s e aplica o ritmo a cada bloco da estrutura de sets.', 'workout.pace': 'Ritmo', 'workout.totalGoal': 'Meta total', 'workout.auto': 'Auto', 'workout.manualRest': 'Descanso manual', 'workout.autoNote': 'O plano troca set e descanso sozinho.', 'workout.manualNote': 'O set encerra na meta; você aciona o próximo set e seu warm-up.', 'workout.pacePerRep': 'Ritmo por repetição', 'workout.restBetween': 'Descanso entre sets', 'workout.calculatedPace': 'Ritmo calculado', 'workout.adjustGroup': 'Ajustar ritmo por grupo', 'workout.general': 'Geral', 'workout.plan': 'Plano', 'workout.projection': 'Projeção total', 'workout.planComplete': 'Plano concluído', 'workout.repetitions': 'repetições', 'workout.includeExtra': 'Incluir adicional', 'workout.revertExtra': 'Reverter adicional', 'workout.resumePacing': 'Retomar pacing', 'workout.pausePacing': 'Pausar pacing', 'workout.nextSet': 'Iniciar próximo set', 'workout.advance': 'Avançar', 'workout.completedSets': 'sets concluídos', 'workout.notes': 'Observações', 'workout.notesPlaceholder': 'Como você se sentiu? O que funcionou?', 'workout.save': 'Salvar treino',
    'history.movedToTrash': 'Treino movido para a lixeira.', 'history.undo': 'Desfazer',
    'data.inventory': '{workouts} treino(s) ativo(s) · {historicalDays} dia(s) histórico(s) importado(s) · {videos} vídeo(s) local(is) · {archived} na lixeira', 'data.videoNote': 'Vídeos não entram no backup JSON; baixe-os individualmente pelo detalhe da performance.',
    'settings.phrases': 'Frases', 'settings.phrasesHint': 'Exibidas alternadamente na tela inicial.', 'settings.phrase': 'Frase {index}', 'settings.deletePhrase': 'Excluir frase {index}', 'settings.restorePhrases': 'Restaurar frases padrão', 'settings.invalidPreset': 'Os sets precisam somar exatamente {target}.',
  },
  'en-US': {
    'language.title': 'Language', 'language.pt': 'Português', 'language.en': 'English', 'language.es': 'Español',
    'nav.home': 'Home', 'nav.workouts': 'Workouts', 'nav.data': 'Data', 'nav.settings': 'Settings', 'nav.label': 'Main navigation',
    'home.register': 'Log workout', 'home.period': 'Summary period', 'home.filter': 'Filter NSB count', 'home.all': 'All', 'home.expand': 'Show targets', 'home.collapse': 'Hide targets', 'home.analysis': 'Analysis mode', 'home.compare': 'Compare years', 'home.evolution': 'Progress', 'home.statistics': 'Statistics',
    'period.all': 'All time', 'period.year': 'This year', 'period.month': 'This month',
    'history.eyebrow': 'Detailed records', 'history.title': 'Workouts', 'history.lead': 'Review, edit, or move detailed records to the bin. Analysis stays on the home screen.', 'history.loading': 'Loading local data…',
    'data.eyebrow': 'Data ownership', 'data.title': 'Backup and restore', 'data.lead': 'Export a complete copy of your history. A safe import merges records by identifier and keeps the latest version.', 'data.export': 'Export JSON backup', 'data.import': 'Import backup', 'data.restore': 'Restore backup', 'data.summary': 'Import merges records. Restore replaces workouts, history, and preferences after creating a safety copy.',
    'settings.eyebrow': 'Settings', 'settings.title': 'Preferences', 'settings.appearance': 'Appearance', 'settings.system': 'System', 'settings.light': 'Light', 'settings.dark': 'Dark', 'settings.text': 'Text', 'settings.fontSize': 'Text size', 'settings.fontScale': '{value}% of default size', 'settings.palette': 'Palette', 'settings.visualPalette': 'Apply to charts and calendar', 'settings.sound': 'Sound', 'settings.soundAlerts': 'Sound alerts', 'settings.soundVolume': 'Alert volume', 'settings.soundProfile': 'Sound profile', 'settings.testSound': 'Test {name}', 'settings.targets': 'Targets', 'settings.targetsHint': 'Tap a target to remove it. Add any value when needed.', 'settings.defaultTargets': 'Default targets', 'settings.removeTarget': 'Remove target {target}', 'settings.addTarget': 'Add target', 'settings.targetExample': 'E.g. 75', 'settings.add': 'Add', 'settings.presets': 'Presets', 'settings.presetTarget': 'Preset target', 'settings.strategiesFor': 'Strategies for {target} NSBs.', 'settings.new': 'New', 'settings.presetName': 'Preset name', 'settings.delete': 'Delete', 'settings.presetGoalType': 'Preset goal type',
    'workout.back': 'Back to home', 'workout.applyPreset': 'Apply preset', 'workout.select': 'Select', 'workout.total': 'Total count', 'workout.timer': 'Timer', 'workout.warmup': 'Warm-up', 'workout.resume': 'Resume', 'workout.start': 'Start', 'workout.pause': 'Pause', 'workout.reset': 'Reset', 'workout.dateTime': 'Date and time', 'workout.totalTime': 'Total time', 'workout.sets': 'Set structure', 'workout.strategy': 'Log the strategy to compare it later.', 'workout.addGroup': 'Add group', 'workout.group': 'Group', 'workout.remove': 'Remove', 'workout.setTotal': 'Set total', 'workout.guidedPacing': 'Guided pacing', 'workout.pacingGoal': 'Pacing goal', 'workout.ready': 'Ready', 'workout.prepare': 'Prepare', 'workout.inSet': 'In set', 'workout.rest': 'Rest', 'workout.paused': 'Paused', 'workout.complete': 'Complete', 'workout.soundAlerts': 'Sound alerts', 'workout.warmupNote': 'The timer starts a {seconds}s warm-up and applies the pace to every set-structure block.', 'workout.pace': 'Pace', 'workout.totalGoal': 'Total goal', 'workout.auto': 'Auto', 'workout.manualRest': 'Manual rest', 'workout.autoNote': 'The plan changes sets and rest automatically.', 'workout.manualNote': 'The set ends at its goal; you trigger the next set and its warm-up.', 'workout.pacePerRep': 'Pace per rep', 'workout.restBetween': 'Rest between sets', 'workout.calculatedPace': 'Calculated pace', 'workout.adjustGroup': 'Adjust pace by group', 'workout.general': 'General', 'workout.plan': 'Plan', 'workout.projection': 'Projected total', 'workout.planComplete': 'Plan complete', 'workout.repetitions': 'repetitions', 'workout.includeExtra': 'Include overtime', 'workout.revertExtra': 'Revert overtime', 'workout.resumePacing': 'Resume pacing', 'workout.pausePacing': 'Pause pacing', 'workout.nextSet': 'Start next set', 'workout.advance': 'Advance', 'workout.completedSets': 'sets completed', 'workout.notes': 'Notes', 'workout.notesPlaceholder': 'How did you feel? What worked?', 'workout.save': 'Save workout',
    'history.movedToTrash': 'Workout moved to the bin.', 'history.undo': 'Undo',
    'data.inventory': '{workouts} active workout(s) · {historicalDays} imported historical day(s) · {videos} local video(s) · {archived} in the bin', 'data.videoNote': 'Videos are not included in the JSON backup; download each one from its performance detail.',
    'settings.phrases': 'Phrases', 'settings.phrasesHint': 'Shown in rotation on the home screen.', 'settings.phrase': 'Phrase {index}', 'settings.deletePhrase': 'Delete phrase {index}', 'settings.restorePhrases': 'Restore default phrases', 'settings.invalidPreset': 'Sets must total exactly {target}.',
  },
  'es-ES': {
    'language.title': 'Idioma', 'language.pt': 'Português', 'language.en': 'English', 'language.es': 'Español',
    'nav.home': 'Inicio', 'nav.workouts': 'Entrenamientos', 'nav.data': 'Datos', 'nav.settings': 'Ajustes', 'nav.label': 'Navegación principal',
    'home.register': 'Registrar entrenamiento', 'home.period': 'Período del resumen', 'home.filter': 'Filtrar cantidad de NSB', 'home.all': 'Todos', 'home.expand': 'Mostrar cantidades', 'home.collapse': 'Ocultar cantidades', 'home.analysis': 'Modo de análisis', 'home.compare': 'Comparar años', 'home.evolution': 'Evolución', 'home.statistics': 'Estadísticas',
    'period.all': 'Todo el período', 'period.year': 'Este año', 'period.month': 'Este mes',
    'history.eyebrow': 'Registros detallados', 'history.title': 'Entrenamientos', 'history.lead': 'Consulta, ajusta o mueve registros detallados a la papelera. El análisis permanece en la pantalla inicial.', 'history.loading': 'Cargando datos locales…',
    'data.eyebrow': 'Propiedad de datos', 'data.title': 'Copia de seguridad y restauración', 'data.lead': 'Exporta una copia completa de tu historial. Una importación segura combina registros por identificador y conserva la versión más reciente.', 'data.export': 'Exportar copia JSON', 'data.import': 'Importar copia', 'data.restore': 'Restaurar copia', 'data.summary': 'Importar combina registros. Restaurar reemplaza entrenamientos, historial y preferencias tras crear una copia de seguridad.',
    'settings.eyebrow': 'Ajustes', 'settings.title': 'Preferencias', 'settings.appearance': 'Apariencia', 'settings.system': 'Automático', 'settings.light': 'Claro', 'settings.dark': 'Oscuro', 'settings.text': 'Texto', 'settings.fontSize': 'Tamaño del texto', 'settings.fontScale': '{value}% del tamaño predeterminado', 'settings.palette': 'Paleta', 'settings.visualPalette': 'Aplicar a gráficos y calendario', 'settings.sound': 'Sonido', 'settings.soundAlerts': 'Avisos sonoros', 'settings.soundVolume': 'Volumen de avisos', 'settings.soundProfile': 'Perfil sonoro', 'settings.testSound': 'Probar {name}', 'settings.targets': 'Metas', 'settings.targetsHint': 'Toca una cantidad para eliminarla. Añade cualquier valor cuando lo necesites.', 'settings.defaultTargets': 'Metas predeterminadas', 'settings.removeTarget': 'Eliminar meta {target}', 'settings.addTarget': 'Añadir meta', 'settings.targetExample': 'Ej.: 75', 'settings.add': 'Añadir', 'settings.presets': 'Presets', 'settings.presetTarget': 'Cantidad del preset', 'settings.strategiesFor': 'Estrategias para {target} NSBs.', 'settings.new': 'Nuevo', 'settings.presetName': 'Nombre del preset', 'settings.delete': 'Eliminar', 'settings.presetGoalType': 'Tipo de meta del preset',
    'workout.back': 'Volver al inicio', 'workout.applyPreset': 'Aplicar preset', 'workout.select': 'Seleccionar', 'workout.total': 'Cantidad total', 'workout.timer': 'Cronómetro', 'workout.warmup': 'Calentamiento', 'workout.resume': 'Reanudar', 'workout.start': 'Iniciar', 'workout.pause': 'Pausar', 'workout.reset': 'Reiniciar', 'workout.dateTime': 'Fecha y hora', 'workout.totalTime': 'Tiempo total', 'workout.sets': 'Estructura de sets', 'workout.strategy': 'Registra la estrategia para compararla más adelante.', 'workout.addGroup': 'Añadir grupo', 'workout.group': 'Grupo', 'workout.remove': 'Eliminar', 'workout.setTotal': 'Total de sets', 'workout.guidedPacing': 'Ritmo guiado', 'workout.pacingGoal': 'Meta de ritmo', 'workout.ready': 'Listo', 'workout.prepare': 'Preparar', 'workout.inSet': 'En set', 'workout.rest': 'Descanso', 'workout.paused': 'Pausado', 'workout.complete': 'Completado', 'workout.soundAlerts': 'Avisos sonoros', 'workout.warmupNote': 'El cronómetro inicia un calentamiento de {seconds}s y aplica el ritmo a cada bloque de sets.', 'workout.pace': 'Ritmo', 'workout.totalGoal': 'Meta total', 'workout.auto': 'Auto', 'workout.manualRest': 'Descanso manual', 'workout.autoNote': 'El plan cambia sets y descansos automáticamente.', 'workout.manualNote': 'El set termina en la meta; tú inicias el siguiente set y su calentamiento.', 'workout.pacePerRep': 'Ritmo por repetición', 'workout.restBetween': 'Descanso entre sets', 'workout.calculatedPace': 'Ritmo calculado', 'workout.adjustGroup': 'Ajustar ritmo por grupo', 'workout.general': 'General', 'workout.plan': 'Plan', 'workout.projection': 'Proyección total', 'workout.planComplete': 'Plan completado', 'workout.repetitions': 'repeticiones', 'workout.includeExtra': 'Incluir adicional', 'workout.revertExtra': 'Revertir adicional', 'workout.resumePacing': 'Reanudar ritmo', 'workout.pausePacing': 'Pausar ritmo', 'workout.nextSet': 'Iniciar siguiente set', 'workout.advance': 'Avanzar', 'workout.completedSets': 'sets completados', 'workout.notes': 'Notas', 'workout.notesPlaceholder': '¿Cómo te sentiste? ¿Qué funcionó?', 'workout.save': 'Guardar entrenamiento',
    'history.movedToTrash': 'Entrenamiento movido a la papelera.', 'history.undo': 'Deshacer',
    'data.inventory': '{workouts} entrenamiento(s) activo(s) · {historicalDays} día(s) histórico(s) importado(s) · {videos} vídeo(s) local(es) · {archived} en la papelera', 'data.videoNote': 'Los vídeos no se incluyen en la copia JSON; descarga cada uno desde el detalle de la performance.',
    'settings.phrases': 'Frases', 'settings.phrasesHint': 'Se muestran alternadamente en la pantalla de inicio.', 'settings.phrase': 'Frase {index}', 'settings.deletePhrase': 'Eliminar frase {index}', 'settings.restorePhrases': 'Restaurar frases predeterminadas', 'settings.invalidPreset': 'Los sets deben sumar exactamente {target}.',
  },
}

export function translate(language: AppLanguage, key: string, values: Record<string, string | number> = {}): string {
  const message = messages[language][key] ?? messages['pt-BR'][key] ?? key
  return message.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`))
}
