export type AppLanguage = 'pt-BR' | 'en-US' | 'es-ES'

const messages: Record<AppLanguage, Record<string, string>> = {
  'pt-BR': {
    'language.title': 'Idioma', 'language.pt': 'Português', 'language.en': 'English', 'language.es': 'Español',
    'nav.home': 'Início', 'nav.workouts': 'Treinos', 'nav.data': 'Dados', 'nav.settings': 'Ajustes', 'nav.label': 'Navegação principal',
    'home.register': 'Registrar treino', 'home.period': 'Período do resumo', 'home.filter': 'Filtrar quantidade de NSBs', 'home.all': 'Todos', 'home.expand': 'Mostrar quantidades', 'home.collapse': 'Recolher quantidades', 'home.analysis': 'Modo de análise', 'home.compare': 'Comparar anos', 'home.evolution': 'Evolução', 'home.statistics': 'Estatísticas',
    'period.all': 'Todo o período', 'period.year': 'Este ano', 'period.month': 'Este mês',
    'history.eyebrow': 'Registros detalhados', 'history.title': 'Treinos', 'history.lead': 'Consulte, ajuste ou mova registros detalhados para a lixeira. As análises ficam concentradas na tela inicial.', 'history.loading': 'Carregando dados locais…',
    'data.eyebrow': 'Propriedade dos dados', 'data.title': 'Backup e restauração', 'data.lead': 'Exporte uma cópia completa do seu histórico. Uma importação segura combina registros pelo identificador e mantém a versão mais recente.', 'data.export': 'Exportar backup JSON', 'data.import': 'Importar backup', 'data.restore': 'Restaurar backup', 'data.summary': 'Importar combina registros. Restaurar substitui treinos, históricos e preferências após criar uma cópia de segurança.',
    'settings.eyebrow': 'Ajustes', 'settings.title': 'Preferências', 'settings.appearance': 'Aparência', 'settings.system': 'Automático', 'settings.light': 'Claro', 'settings.dark': 'Escuro', 'settings.text': 'Texto', 'settings.fontSize': 'Tamanho do texto', 'settings.fontScale': '{value}% do tamanho padrão', 'settings.palette': 'Paleta', 'settings.visualPalette': 'Aplicar nos gráficos e calendário', 'settings.sound': 'Som', 'settings.soundAlerts': 'Avisos sonoros', 'settings.soundVolume': 'Volume dos avisos', 'settings.soundProfile': 'Perfil sonoro', 'settings.testSound': 'Testar perfil {name}', 'settings.targets': 'Metas', 'settings.targetsHint': 'Toque em uma quantidade para removê-la. Adicione qualquer valor quando precisar.', 'settings.defaultTargets': 'Metas padrão', 'settings.removeTarget': 'Remover meta {target}', 'settings.addTarget': 'Adicionar meta', 'settings.targetExample': 'Ex.: 75', 'settings.add': 'Adicionar', 'settings.presets': 'Presets', 'settings.presetTarget': 'Quantidade do preset', 'settings.strategiesFor': 'Estratégias para {target} NSBs.', 'settings.new': 'Novo', 'settings.presetName': 'Nome do preset', 'settings.delete': 'Excluir', 'settings.presetGoalType': 'Tipo de meta do preset',
    'workout.back': 'Voltar ao início', 'workout.applyPreset': 'Aplicar preset', 'workout.select': 'Selecionar', 'workout.total': 'Quantidade total', 'workout.timer': 'Cronômetro', 'workout.warmup': 'Warm-up', 'workout.resume': 'Retomar', 'workout.start': 'Iniciar', 'workout.pause': 'Pausar', 'workout.reset': 'Zerar', 'workout.dateTime': 'Data e hora', 'workout.totalTime': 'Tempo total', 'workout.sets': 'Estrutura de sets', 'workout.strategy': 'Registre a estratégia para compará-la no futuro.', 'workout.addGroup': 'Adicionar grupo', 'workout.group': 'Grupo', 'workout.remove': 'Remover', 'workout.setTotal': 'Total dos sets', 'workout.guidedPacing': 'Pacing guiado', 'workout.pacingGoal': 'Meta de pacing', 'workout.ready': 'Pronto', 'workout.prepare': 'Preparar', 'workout.inSet': 'Em set', 'workout.rest': 'Descanso', 'workout.paused': 'Pausado', 'workout.complete': 'Concluído', 'workout.soundAlerts': 'Avisos sonoros', 'workout.warmupNote': 'O cronômetro inicia o warm-up de {seconds}s e aplica o ritmo a cada bloco da estrutura de sets.', 'workout.pace': 'Ritmo', 'workout.totalGoal': 'Meta total', 'workout.auto': 'Auto', 'workout.manualRest': 'Descanso manual', 'workout.autoNote': 'O plano troca set e descanso sozinho.', 'workout.manualNote': 'O set encerra na meta; você aciona o próximo set e seu warm-up.', 'workout.pacePerRep': 'Ritmo por repetição', 'workout.restBetween': 'Descanso entre sets', 'workout.calculatedPace': 'Ritmo calculado', 'workout.adjustGroup': 'Ajustar ritmo por grupo', 'workout.general': 'Geral', 'workout.plan': 'Plano', 'workout.projection': 'Projeção total', 'workout.planComplete': 'Plano concluído', 'workout.repetitions': 'repetições', 'workout.includeExtra': 'Incluir adicional', 'workout.revertExtra': 'Reverter adicional', 'workout.resumePacing': 'Retomar pacing', 'workout.pausePacing': 'Pausar pacing', 'workout.nextSet': 'Iniciar próximo set', 'workout.advance': 'Avançar', 'workout.completedSets': 'sets concluídos', 'workout.notes': 'Observações', 'workout.notesPlaceholder': 'Como você se sentiu? O que funcionou?', 'workout.save': 'Salvar treino',
    'history.movedToTrash': 'Treino movido para a lixeira.', 'history.undo': 'Desfazer', 'history.empty': 'Nenhum treino ou volume histórico registrado ainda.', 'history.importedVolume': 'Volume histórico importado', 'history.noTimeSets': 'Sem tempo/sets', 'history.delete': 'Excluir', 'history.trash': 'Lixeira', 'history.archived': 'Treinos arquivados', 'history.selectAll': 'Selecionar todos', 'history.restoreSelected': 'Restaurar selecionados', 'history.deleteSelected': 'Excluir selecionados', 'history.selectWorkout': 'Selecionar treino de {target} NSBs', 'history.restore': 'Restaurar',
    'data.inventory': '{workouts} treino(s) ativo(s) · {historicalDays} dia(s) histórico(s) importado(s) · {videos} vídeo(s) local(is) · {archived} na lixeira', 'data.videoNote': 'Vídeos não entram no backup JSON; baixe-os individualmente pelo detalhe da performance.',
    'settings.phrases': 'Frases', 'settings.phrasesHint': 'Exibidas alternadamente na tela inicial.', 'settings.phrase': 'Frase {index}', 'settings.deletePhrase': 'Excluir frase {index}', 'settings.restorePhrases': 'Restaurar frases padrão', 'settings.invalidPreset': 'Os sets precisam somar exatamente {target}.',
    'charts.emptyPeriod': 'Registre ou importe dados neste período para visualizar o gráfico.', 'charts.volumeYear': 'Volume por ano', 'charts.volumeMonth': 'Volume por mês', 'charts.scale': 'Escala do gráfico', 'charts.evolutionScale': 'Escala do gráfico de evolução', 'charts.back': 'Voltar', 'charts.dailyVolume': 'volume diário', 'charts.dailyAria': '{day} de {month}: {total} NSBs', 'charts.record': 'Recorde: {targets} NSBs', 'charts.consistency': 'Constância', 'charts.lastWeeks': 'Últimas 44 semanas', 'charts.less': 'Menos', 'charts.more': 'Mais',
    'stats.performance': 'Desempenho', 'stats.timeByTarget': 'Tempo por quantidade', 'stats.workoutsPerformances': 'Treinos e performances', 'stats.records': '{count} registro(s)', 'stats.best': 'Melhor', 'stats.worst': 'Pior', 'stats.average': 'Média', 'stats.median': 'Mediana', 'stats.averagePace': 'Ritmo médio', 'stats.setPace': 'Ritmo em set', 'stats.guidedWorkouts': '{count} treino(s) guiado(s)', 'stats.openBest': 'Abrir o volume diário do melhor tempo de {target} NSBs', 'stats.empty': 'Registre um treino com tempo para gerar estatísticas de desempenho.', 'stats.strategyEmpty': 'Adicione a estrutura de sets aos treinos para comparar estratégias.', 'stats.strategies': 'Estratégias', 'stats.timeBySets': 'Tempo por estrutura de sets',
    'comparison.empty': 'Registre ou importe dados para comparar anos.', 'comparison.title': 'Comparação mês a mês', 'comparison.showAll': 'Mostrar todos os anos', 'comparison.download': 'Baixar gráfico', 'comparison.aria': 'Volume mensal comparado entre anos',
    'detail.eyebrow': 'Detalhe do dia', 'detail.close': 'Fechar', 'detail.registeredVolume': 'Volume registrado', 'detail.workouts': 'Treinos detalhados', 'detail.performances': 'Performances registradas', 'detail.attachVideo': 'Anexar vídeo', 'detail.editWorkout': 'Editar treino', 'detail.editPerformance': 'Editar performance histórica', 'detail.addPerformance': 'Adicionar performance histórica', 'detail.editHint': 'Atualize tempo, sets e observações do treino.', 'detail.addHint': 'Registra tempo, estrutura de sets e observações sem somar volume ao dia.', 'detail.target': 'Quantidade', 'detail.time': 'Tempo', 'detail.setCount': 'Número de sets', 'detail.repsPerSet': 'NSBs por set', 'detail.save': 'Salvar {item}', 'detail.workout': 'treino', 'detail.performance': 'performance', 'detail.invalidDuration': 'Use mm:ss ou h:mm:ss, por exemplo 18:42 ou 1:18:42.', 'detail.invalidSets': 'Os sets somam {total} NSBs, mas a performance é de {target}.', 'detail.invalidVideo': 'Selecione um arquivo de vídeo.', 'detail.videoTooLarge': 'O vídeo deve ter no máximo 250 MB para armazenamento local.', 'detail.download': 'Baixar',
  },
  'en-US': {
    'language.title': 'Language', 'language.pt': 'Português', 'language.en': 'English', 'language.es': 'Español',
    'nav.home': 'Home', 'nav.workouts': 'Workouts', 'nav.data': 'Data', 'nav.settings': 'Settings', 'nav.label': 'Main navigation',
    'home.register': 'Log workout', 'home.period': 'Summary period', 'home.filter': 'Filter NSB count', 'home.all': 'All', 'home.expand': 'Show targets', 'home.collapse': 'Hide targets', 'home.analysis': 'Analysis mode', 'home.compare': 'Compare years', 'home.evolution': 'Progress', 'home.statistics': 'Statistics',
    'period.all': 'All time', 'period.year': 'This year', 'period.month': 'This month',
    'history.eyebrow': 'Detailed records', 'history.title': 'Workouts', 'history.lead': 'Review, edit, or move detailed records to the bin. Analysis stays on the home screen.', 'history.loading': 'Loading local data…',
    'data.eyebrow': 'Data ownership', 'data.title': 'Backup and restore', 'data.lead': 'Export a complete copy of your history. A safe import merges records by identifier and keeps the latest version.', 'data.export': 'Export JSON backup', 'data.import': 'Import backup', 'data.restore': 'Restore backup', 'data.summary': 'Import merges records. Restore replaces workouts, history, and preferences after creating a safety copy.',
    'settings.eyebrow': 'Settings', 'settings.title': 'Preferences', 'settings.appearance': 'Appearance', 'settings.system': 'System', 'settings.light': 'Light', 'settings.dark': 'Dark', 'settings.text': 'Text', 'settings.fontSize': 'Text size', 'settings.fontScale': '{value}% of default size', 'settings.palette': 'Palette', 'settings.visualPalette': 'Apply to charts and calendar', 'settings.sound': 'Sound', 'settings.soundAlerts': 'Sound alerts', 'settings.soundVolume': 'Alert volume', 'settings.soundProfile': 'Sound profile', 'settings.testSound': 'Test {name}', 'settings.targets': 'Targets', 'settings.targetsHint': 'Tap a target to remove it. Add any value when needed.', 'settings.defaultTargets': 'Default targets', 'settings.removeTarget': 'Remove target {target}', 'settings.addTarget': 'Add target', 'settings.targetExample': 'E.g. 75', 'settings.add': 'Add', 'settings.presets': 'Presets', 'settings.presetTarget': 'Preset target', 'settings.strategiesFor': 'Strategies for {target} NSBs.', 'settings.new': 'New', 'settings.presetName': 'Preset name', 'settings.delete': 'Delete', 'settings.presetGoalType': 'Preset goal type',
    'workout.back': 'Back to home', 'workout.applyPreset': 'Apply preset', 'workout.select': 'Select', 'workout.total': 'Total count', 'workout.timer': 'Timer', 'workout.warmup': 'Warm-up', 'workout.resume': 'Resume', 'workout.start': 'Start', 'workout.pause': 'Pause', 'workout.reset': 'Reset', 'workout.dateTime': 'Date and time', 'workout.totalTime': 'Total time', 'workout.sets': 'Set structure', 'workout.strategy': 'Log the strategy to compare it later.', 'workout.addGroup': 'Add group', 'workout.group': 'Group', 'workout.remove': 'Remove', 'workout.setTotal': 'Set total', 'workout.guidedPacing': 'Guided pacing', 'workout.pacingGoal': 'Pacing goal', 'workout.ready': 'Ready', 'workout.prepare': 'Prepare', 'workout.inSet': 'In set', 'workout.rest': 'Rest', 'workout.paused': 'Paused', 'workout.complete': 'Complete', 'workout.soundAlerts': 'Sound alerts', 'workout.warmupNote': 'The timer starts a {seconds}s warm-up and applies the pace to every set-structure block.', 'workout.pace': 'Pace', 'workout.totalGoal': 'Total goal', 'workout.auto': 'Auto', 'workout.manualRest': 'Manual rest', 'workout.autoNote': 'The plan changes sets and rest automatically.', 'workout.manualNote': 'The set ends at its goal; you trigger the next set and its warm-up.', 'workout.pacePerRep': 'Pace per rep', 'workout.restBetween': 'Rest between sets', 'workout.calculatedPace': 'Calculated pace', 'workout.adjustGroup': 'Adjust pace by group', 'workout.general': 'General', 'workout.plan': 'Plan', 'workout.projection': 'Projected total', 'workout.planComplete': 'Plan complete', 'workout.repetitions': 'repetitions', 'workout.includeExtra': 'Include overtime', 'workout.revertExtra': 'Revert overtime', 'workout.resumePacing': 'Resume pacing', 'workout.pausePacing': 'Pause pacing', 'workout.nextSet': 'Start next set', 'workout.advance': 'Advance', 'workout.completedSets': 'sets completed', 'workout.notes': 'Notes', 'workout.notesPlaceholder': 'How did you feel? What worked?', 'workout.save': 'Save workout',
    'history.movedToTrash': 'Workout moved to the bin.', 'history.undo': 'Undo', 'history.empty': 'No workout or historical volume recorded yet.', 'history.importedVolume': 'Imported historical volume', 'history.noTimeSets': 'No time/sets', 'history.delete': 'Delete', 'history.trash': 'Bin', 'history.archived': 'Archived workouts', 'history.selectAll': 'Select all', 'history.restoreSelected': 'Restore selected', 'history.deleteSelected': 'Delete selected', 'history.selectWorkout': 'Select {target} NSBs workout', 'history.restore': 'Restore',
    'data.inventory': '{workouts} active workout(s) · {historicalDays} imported historical day(s) · {videos} local video(s) · {archived} in the bin', 'data.videoNote': 'Videos are not included in the JSON backup; download each one from its performance detail.',
    'settings.phrases': 'Phrases', 'settings.phrasesHint': 'Shown in rotation on the home screen.', 'settings.phrase': 'Phrase {index}', 'settings.deletePhrase': 'Delete phrase {index}', 'settings.restorePhrases': 'Restore default phrases', 'settings.invalidPreset': 'Sets must total exactly {target}.',
    'charts.emptyPeriod': 'Log or import data in this period to view the chart.', 'charts.volumeYear': 'Volume by year', 'charts.volumeMonth': 'Volume by month', 'charts.scale': 'Chart scale', 'charts.evolutionScale': 'Progress chart scale', 'charts.back': 'Back', 'charts.dailyVolume': 'daily volume', 'charts.dailyAria': '{day} {month}: {total} NSBs', 'charts.record': 'Record: {targets} NSBs', 'charts.consistency': 'Consistency', 'charts.lastWeeks': 'Last 44 weeks', 'charts.less': 'Less', 'charts.more': 'More',
    'stats.performance': 'Performance', 'stats.timeByTarget': 'Time by target', 'stats.workoutsPerformances': 'Workouts and performances', 'stats.records': '{count} record(s)', 'stats.best': 'Best', 'stats.worst': 'Worst', 'stats.average': 'Average', 'stats.median': 'Median', 'stats.averagePace': 'Average pace', 'stats.setPace': 'Set pace', 'stats.guidedWorkouts': '{count} guided workout(s)', 'stats.openBest': 'Open daily volume for the best {target} NSBs time', 'stats.empty': 'Log a timed workout to generate performance statistics.', 'stats.strategyEmpty': 'Add set structures to workouts to compare strategies.', 'stats.strategies': 'Strategies', 'stats.timeBySets': 'Time by set structure',
    'comparison.empty': 'Log or import data to compare years.', 'comparison.title': 'Month-by-month comparison', 'comparison.showAll': 'Show all years', 'comparison.download': 'Download chart', 'comparison.aria': 'Monthly volume compared across years',
    'detail.eyebrow': 'Day detail', 'detail.close': 'Close', 'detail.registeredVolume': 'Recorded volume', 'detail.workouts': 'Detailed workouts', 'detail.performances': 'Recorded performances', 'detail.attachVideo': 'Attach video', 'detail.editWorkout': 'Edit workout', 'detail.editPerformance': 'Edit historical performance', 'detail.addPerformance': 'Add historical performance', 'detail.editHint': 'Update the workout time, sets, and notes.', 'detail.addHint': 'Log time, set structure, and notes without adding volume to the day.', 'detail.target': 'Target', 'detail.time': 'Time', 'detail.setCount': 'Number of sets', 'detail.repsPerSet': 'NSBs per set', 'detail.save': 'Save {item}', 'detail.workout': 'workout', 'detail.performance': 'performance', 'detail.invalidDuration': 'Use mm:ss or h:mm:ss, for example 18:42 or 1:18:42.', 'detail.invalidSets': 'Sets total {total} NSBs, but the performance is {target}.', 'detail.invalidVideo': 'Select a video file.', 'detail.videoTooLarge': 'Video must be at most 250 MB for local storage.', 'detail.download': 'Download',
  },
  'es-ES': {
    'language.title': 'Idioma', 'language.pt': 'Português', 'language.en': 'English', 'language.es': 'Español',
    'nav.home': 'Inicio', 'nav.workouts': 'Entrenamientos', 'nav.data': 'Datos', 'nav.settings': 'Ajustes', 'nav.label': 'Navegación principal',
    'home.register': 'Registrar entrenamiento', 'home.period': 'Período del resumen', 'home.filter': 'Filtrar cantidad de NSB', 'home.all': 'Todos', 'home.expand': 'Mostrar cantidades', 'home.collapse': 'Ocultar cantidades', 'home.analysis': 'Modo de análisis', 'home.compare': 'Comparar años', 'home.evolution': 'Evolución', 'home.statistics': 'Estadísticas',
    'period.all': 'Todo el período', 'period.year': 'Este año', 'period.month': 'Este mes',
    'history.eyebrow': 'Registros detallados', 'history.title': 'Entrenamientos', 'history.lead': 'Consulta, ajusta o mueve registros detallados a la papelera. El análisis permanece en la pantalla inicial.', 'history.loading': 'Cargando datos locales…',
    'data.eyebrow': 'Propiedad de datos', 'data.title': 'Copia de seguridad y restauración', 'data.lead': 'Exporta una copia completa de tu historial. Una importación segura combina registros por identificador y conserva la versión más reciente.', 'data.export': 'Exportar copia JSON', 'data.import': 'Importar copia', 'data.restore': 'Restaurar copia', 'data.summary': 'Importar combina registros. Restaurar reemplaza entrenamientos, historial y preferencias tras crear una copia de seguridad.',
    'settings.eyebrow': 'Ajustes', 'settings.title': 'Preferencias', 'settings.appearance': 'Apariencia', 'settings.system': 'Automático', 'settings.light': 'Claro', 'settings.dark': 'Oscuro', 'settings.text': 'Texto', 'settings.fontSize': 'Tamaño del texto', 'settings.fontScale': '{value}% del tamaño predeterminado', 'settings.palette': 'Paleta', 'settings.visualPalette': 'Aplicar a gráficos y calendario', 'settings.sound': 'Sonido', 'settings.soundAlerts': 'Avisos sonoros', 'settings.soundVolume': 'Volumen de avisos', 'settings.soundProfile': 'Perfil sonoro', 'settings.testSound': 'Probar {name}', 'settings.targets': 'Metas', 'settings.targetsHint': 'Toca una cantidad para eliminarla. Añade cualquier valor cuando lo necesites.', 'settings.defaultTargets': 'Metas predeterminadas', 'settings.removeTarget': 'Eliminar meta {target}', 'settings.addTarget': 'Añadir meta', 'settings.targetExample': 'Ej.: 75', 'settings.add': 'Añadir', 'settings.presets': 'Presets', 'settings.presetTarget': 'Cantidad del preset', 'settings.strategiesFor': 'Estrategias para {target} NSBs.', 'settings.new': 'Nuevo', 'settings.presetName': 'Nombre del preset', 'settings.delete': 'Eliminar', 'settings.presetGoalType': 'Tipo de meta del preset',
    'workout.back': 'Volver al inicio', 'workout.applyPreset': 'Aplicar preset', 'workout.select': 'Seleccionar', 'workout.total': 'Cantidad total', 'workout.timer': 'Cronómetro', 'workout.warmup': 'Calentamiento', 'workout.resume': 'Reanudar', 'workout.start': 'Iniciar', 'workout.pause': 'Pausar', 'workout.reset': 'Reiniciar', 'workout.dateTime': 'Fecha y hora', 'workout.totalTime': 'Tiempo total', 'workout.sets': 'Estructura de sets', 'workout.strategy': 'Registra la estrategia para compararla más adelante.', 'workout.addGroup': 'Añadir grupo', 'workout.group': 'Grupo', 'workout.remove': 'Eliminar', 'workout.setTotal': 'Total de sets', 'workout.guidedPacing': 'Ritmo guiado', 'workout.pacingGoal': 'Meta de ritmo', 'workout.ready': 'Listo', 'workout.prepare': 'Preparar', 'workout.inSet': 'En set', 'workout.rest': 'Descanso', 'workout.paused': 'Pausado', 'workout.complete': 'Completado', 'workout.soundAlerts': 'Avisos sonoros', 'workout.warmupNote': 'El cronómetro inicia un calentamiento de {seconds}s y aplica el ritmo a cada bloque de sets.', 'workout.pace': 'Ritmo', 'workout.totalGoal': 'Meta total', 'workout.auto': 'Auto', 'workout.manualRest': 'Descanso manual', 'workout.autoNote': 'El plan cambia sets y descansos automáticamente.', 'workout.manualNote': 'El set termina en la meta; tú inicias el siguiente set y su calentamiento.', 'workout.pacePerRep': 'Ritmo por repetición', 'workout.restBetween': 'Descanso entre sets', 'workout.calculatedPace': 'Ritmo calculado', 'workout.adjustGroup': 'Ajustar ritmo por grupo', 'workout.general': 'General', 'workout.plan': 'Plan', 'workout.projection': 'Proyección total', 'workout.planComplete': 'Plan completado', 'workout.repetitions': 'repeticiones', 'workout.includeExtra': 'Incluir adicional', 'workout.revertExtra': 'Revertir adicional', 'workout.resumePacing': 'Reanudar ritmo', 'workout.pausePacing': 'Pausar ritmo', 'workout.nextSet': 'Iniciar siguiente set', 'workout.advance': 'Avanzar', 'workout.completedSets': 'sets completados', 'workout.notes': 'Notas', 'workout.notesPlaceholder': '¿Cómo te sentiste? ¿Qué funcionó?', 'workout.save': 'Guardar entrenamiento',
    'history.movedToTrash': 'Entrenamiento movido a la papelera.', 'history.undo': 'Deshacer', 'history.empty': 'Aún no hay entrenamiento ni volumen histórico registrado.', 'history.importedVolume': 'Volumen histórico importado', 'history.noTimeSets': 'Sin tiempo/sets', 'history.delete': 'Eliminar', 'history.trash': 'Papelera', 'history.archived': 'Entrenamientos archivados', 'history.selectAll': 'Seleccionar todos', 'history.restoreSelected': 'Restaurar seleccionados', 'history.deleteSelected': 'Eliminar seleccionados', 'history.selectWorkout': 'Seleccionar entrenamiento de {target} NSBs', 'history.restore': 'Restaurar',
    'data.inventory': '{workouts} entrenamiento(s) activo(s) · {historicalDays} día(s) histórico(s) importado(s) · {videos} vídeo(s) local(es) · {archived} en la papelera', 'data.videoNote': 'Los vídeos no se incluyen en la copia JSON; descarga cada uno desde el detalle de la performance.',
    'settings.phrases': 'Frases', 'settings.phrasesHint': 'Se muestran alternadamente en la pantalla de inicio.', 'settings.phrase': 'Frase {index}', 'settings.deletePhrase': 'Eliminar frase {index}', 'settings.restorePhrases': 'Restaurar frases predeterminadas', 'settings.invalidPreset': 'Los sets deben sumar exactamente {target}.',
    'charts.emptyPeriod': 'Registra o importa datos en este período para ver el gráfico.', 'charts.volumeYear': 'Volumen por año', 'charts.volumeMonth': 'Volumen por mes', 'charts.scale': 'Escala del gráfico', 'charts.evolutionScale': 'Escala del gráfico de evolución', 'charts.back': 'Volver', 'charts.dailyVolume': 'volumen diario', 'charts.dailyAria': '{day} de {month}: {total} NSBs', 'charts.record': 'Récord: {targets} NSBs', 'charts.consistency': 'Constancia', 'charts.lastWeeks': 'Últimas 44 semanas', 'charts.less': 'Menos', 'charts.more': 'Más',
    'stats.performance': 'Rendimiento', 'stats.timeByTarget': 'Tiempo por cantidad', 'stats.workoutsPerformances': 'Entrenamientos y performances', 'stats.records': '{count} registro(s)', 'stats.best': 'Mejor', 'stats.worst': 'Peor', 'stats.average': 'Promedio', 'stats.median': 'Mediana', 'stats.averagePace': 'Ritmo promedio', 'stats.setPace': 'Ritmo en set', 'stats.guidedWorkouts': '{count} entrenamiento(s) guiado(s)', 'stats.openBest': 'Abrir volumen diario del mejor tiempo de {target} NSBs', 'stats.empty': 'Registra un entrenamiento cronometrado para generar estadísticas de rendimiento.', 'stats.strategyEmpty': 'Añade estructuras de sets a los entrenamientos para comparar estrategias.', 'stats.strategies': 'Estrategias', 'stats.timeBySets': 'Tiempo por estructura de sets',
    'comparison.empty': 'Registra o importa datos para comparar años.', 'comparison.title': 'Comparación mes a mes', 'comparison.showAll': 'Mostrar todos los años', 'comparison.download': 'Descargar gráfico', 'comparison.aria': 'Volumen mensual comparado entre años',
    'detail.eyebrow': 'Detalle del día', 'detail.close': 'Cerrar', 'detail.registeredVolume': 'Volumen registrado', 'detail.workouts': 'Entrenamientos detallados', 'detail.performances': 'Performances registradas', 'detail.attachVideo': 'Adjuntar vídeo', 'detail.editWorkout': 'Editar entrenamiento', 'detail.editPerformance': 'Editar performance histórica', 'detail.addPerformance': 'Añadir performance histórica', 'detail.editHint': 'Actualiza el tiempo, los sets y las notas del entrenamiento.', 'detail.addHint': 'Registra tiempo, estructura de sets y notas sin sumar volumen al día.', 'detail.target': 'Cantidad', 'detail.time': 'Tiempo', 'detail.setCount': 'Número de sets', 'detail.repsPerSet': 'NSBs por set', 'detail.save': 'Guardar {item}', 'detail.workout': 'entrenamiento', 'detail.performance': 'performance', 'detail.invalidDuration': 'Usa mm:ss o h:mm:ss, por ejemplo 18:42 o 1:18:42.', 'detail.invalidSets': 'Los sets suman {total} NSBs, pero la performance es de {target}.', 'detail.invalidVideo': 'Selecciona un archivo de vídeo.', 'detail.videoTooLarge': 'El vídeo debe tener como máximo 250 MB para almacenamiento local.', 'detail.download': 'Descargar',
  },
}

export function translate(language: AppLanguage, key: string, values: Record<string, string | number> = {}): string {
  const message = messages[language][key] ?? messages['pt-BR'][key] ?? key
  return message.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`))
}
