package com.santanads.nsb;

import android.app.*;
import android.content.Intent;
import android.media.AudioManager;
import android.media.ToneGenerator;
import android.os.*;

public class PacingAudioService extends Service {
    static final String START = "com.santanads.nsb.START", SIGNAL = "com.santanads.nsb.SIGNAL", SCHEDULE = "com.santanads.nsb.SCHEDULE", CANCEL = "com.santanads.nsb.CANCEL";
    private static final String CHANNEL = "nsb-pacing"; private static final int ID = 2401;
    private final Handler handler = new Handler(Looper.getMainLooper()); private ToneGenerator tones;
    @Override public void onCreate() { super.onCreate(); if (Build.VERSION.SDK_INT >= 26) ((NotificationManager) getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(new NotificationChannel(CHANNEL, "Pacing em andamento", NotificationManager.IMPORTANCE_LOW)); tones = new ToneGenerator(AudioManager.STREAM_ALARM, 100); startForeground(ID, notification()); }
    @Override public int onStartCommand(Intent intent, int flags, int startId) {
        String action = intent == null ? START : intent.getAction(); if (SIGNAL.equals(action)) play(intent.getStringExtra("kind"), intent.getStringExtra("profile"), intent.getIntExtra("volume", 100));
        if (SCHEDULE.equals(action)) schedule(intent.getLongArrayExtra("delays"), intent.getStringArrayExtra("kinds"), intent.getStringExtra("profile"), intent.getIntExtra("volume", 100));
        if (CANCEL.equals(action)) handler.removeCallbacksAndMessages(null); return START_NOT_STICKY;
    }
    private void schedule(long[] delays, String[] kinds, String profile, int volume) { handler.removeCallbacksAndMessages(null); if (delays == null || kinds == null) return; long finalDelay = 0; for (int i = 0; i < Math.min(delays.length, kinds.length); i++) { final String kind = kinds[i]; final long delay = Math.max(0, delays[i]); finalDelay = Math.max(finalDelay, delay); handler.postDelayed(() -> play(kind, profile, volume), delay); } handler.postDelayed(this::stopSelf, finalDelay + 1_000); }
    private void play(String kind, String profile, int volume) { int duration = "rep".equals(kind) ? 90 : "complete".equals(kind) ? 520 : "set".equals(kind) ? 260 : 180; int[] profileTones = profileTones(profile); int offset = "warmup".equals(kind) ? 0 : "set".equals(kind) ? 1 : "rest".equals(kind) ? 2 : "complete".equals(kind) ? 3 : 4; int tone = profileTones[offset]; if (tones != null) tones.release(); tones = new ToneGenerator(AudioManager.STREAM_ALARM, Math.max(1, Math.min(100, volume))); tones.startTone(tone, duration); }
    private int[] profileTones(String profile) { if ("command".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_9, ToneGenerator.TONE_DTMF_3, ToneGenerator.TONE_DTMF_0, ToneGenerator.TONE_DTMF_7}; if ("pulse".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_2, ToneGenerator.TONE_DTMF_8, ToneGenerator.TONE_DTMF_4, ToneGenerator.TONE_DTMF_9, ToneGenerator.TONE_DTMF_6}; if ("cardio".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_3, ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_5, ToneGenerator.TONE_DTMF_2}; if ("beacon".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_4, ToneGenerator.TONE_DTMF_7, ToneGenerator.TONE_DTMF_2, ToneGenerator.TONE_DTMF_9, ToneGenerator.TONE_DTMF_5}; if ("siren".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_3, ToneGenerator.TONE_DTMF_8, ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_0, ToneGenerator.TONE_DTMF_6}; if ("alarm".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_9, ToneGenerator.TONE_DTMF_0, ToneGenerator.TONE_DTMF_5, ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD, ToneGenerator.TONE_DTMF_8}; if ("horn".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_2, ToneGenerator.TONE_DTMF_4, ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_6, ToneGenerator.TONE_DTMF_3}; if ("bass".equals(profile)) return new int[]{ToneGenerator.TONE_DTMF_0, ToneGenerator.TONE_DTMF_2, ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_4, ToneGenerator.TONE_DTMF_0}; if ("quiet".equals(profile)) return new int[]{ToneGenerator.TONE_PROP_BEEP, ToneGenerator.TONE_DTMF_3, ToneGenerator.TONE_DTMF_1, ToneGenerator.TONE_DTMF_5, ToneGenerator.TONE_DTMF_2}; return new int[]{ToneGenerator.TONE_PROP_BEEP, ToneGenerator.TONE_DTMF_5, ToneGenerator.TONE_DTMF_2, ToneGenerator.TONE_CDMA_ALERT_CALL_GUARD, ToneGenerator.TONE_DTMF_8}; }
    private Notification notification() { Intent open = new Intent(this, MainActivity.class); PendingIntent pending = PendingIntent.getActivity(this, 0, open, PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE); Notification.Builder builder = Build.VERSION.SDK_INT >= 26 ? new Notification.Builder(this, CHANNEL) : new Notification.Builder(this); return builder.setSmallIcon(android.R.drawable.ic_media_play).setContentTitle("Navy Seal Burpees").setContentText("Pacing ativo em segundo plano").setContentIntent(pending).setOngoing(true).build(); }
    @Override public void onDestroy() { handler.removeCallbacksAndMessages(null); if (tones != null) tones.release(); super.onDestroy(); }
    @Override public android.os.IBinder onBind(Intent intent) { return null; }
}
